# Generated by Django 5.2.9 on 2025-12-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('terminated', 'Terminated')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('terminated', 'Terminated')], default='active', max_length=20),
        ),
    ]
